USE master;
GO

IF DB_ID(N'QL_XACMINHTHITHE') IS NOT NULL
BEGIN
    ALTER DATABASE QL_XACMINHTHITHE
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;

    DROP DATABASE QL_XACMINHTHITHE;
END;
GO

CREATE DATABASE QL_XACMINHTHITHE;
GO

USE QL_XACMINHTHITHE;
GO